#!/usr/bin/env bash
# Configure domain zone so sd points to your lb ip
sub (){
    SUBDOMAIN="$2"
    COMPLETE="$2.$1"
    INFO="$(dig "$COMPLETE" | grep 'ANSWER SECTION' -A1 | awk 'NR==2')"
    IP=$(echo "$INFO" | awk '{print $5}')
    RECORD=$(echo "$INFO" | awk '{print $4}')
    echo The subdomain "$SUBDOMAIN" is a "$RECORD" record and points to "$IP"
}

if [[ -z "$2" ]]
then   
    SUB="www lb-01 web-01 web-02"
    for i in $SUB;
    do
	sub "$1" "$i"
    done
else
    sub "$1" "$2"
fi

exit 0
