#!/usr/bin/env bash
# Configure domain zone so subdomain www points to your lb ip

sub () {
    LINE="$(dig "$2.$1" | grep 'ANSWER SECTION' -A1 | awk 'NR==2')"
    RECORD=$(echo "$LINE" | awk '{print $4}')
    DESTINATION=$(echo "$LINE" | awk '{print $5}')
    echo "The subdomain $2 is a $RECORD record and points to $DESTINATION"
}

if [[ -z "$2" ]]
then
  SUB="www lb-01 web-01 web-02"
  for i in $SUB;
  do
    sub "$1" "$i"
  done
else
  sub "$1" "$2"
fi

exit 0
