#!/usr/bin/env bash
# Configure domain zone so sd points to your lb ip
func (){
    SUBDOMAIN="$2"
    ALL="$2.$1"
    LINE="$(dig "$ALL" | grep 'ANSWER SECTION' -A1 | awk 'NR==2')"
    RECORD=$(echo "$LINE" | awk '{print $4}')
    DESTINATION=$(echo "$LINE" | awk '{print $5}')
    echo The subdomain "$SUBDOMAIN" is a "$RECORD" record and points to "$DESTINATION"
}

if [[ -z "$2" ]]
then
    SUB="www lb-01 web-01 web-02"
    for i in $SUB;
    do
        func "$1" "$i"
    done
  else
    func "$1" "$2"
fi

exit 0
