#!/usr/bin/env bash
# HTTP response contains a custom header (on web-01 and web-02)

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo sed -i "46i\add_header X-Served-By $HOSTNAME ;" /etc/nginx/sites-available/default
sudo service nginx start
