#!/usr/bin/env bash
# Comment
trap "echo I hate the kill command" SIGTERM
trap "echo Y U no love me?!" SIGINT
echo $$ > /var/run/holbertonscript.pid
while :
do
echo "To infinity and beyond"
sleep 2
done
rm /var/run/holbertonscript.pid
