#!/usr/bin/env bash
# Comment
trap "echo I hate the kill command; rm /var/run/holbertonscript.pid; exit 0" SIGTERM
trap "echo Y U no love me?!" SIGINT
echo $$ > /var/run/holbertonscript.pid
while :
do
echo "To infinity and beyond"
done
trap "rm /var/run/holbertonscript.pid; exit 0" SIGQUIT
