#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
i=1

while [ $i -le 20 ]
do
    echo "$i"
    case $i in
        4)
            printf "bad luck from China\n"
            ;;
        9)
            printf "bad luck from Japan\n"
            ;;
        17)
            printf "bad luck from Italy\n"
            ;;
    esac
    ((i++))
done
