#!/usr/bin/env bash
# Run Nginx as Nginx
sudo pkill -o apache2
chmod 744 /etc/nginx/nginx.conf
sudo sed -i "3i\\n user nginx;" /etc/nginx/nginx.conf
sudo sed -i "s/8080/80/g" /etc/nginx/sites-available/default
sudo service nginx restart
