#!/usr/bin/env bash
# Configure Nginx to serve your page from the route /airbnb-onepage/
server {
    listen 80;
    server_name 35.196.122.68;
    add_header X-Served-By 2100-web-01;
    
    location = /airbnb-onepage/ {
        proxy_pass http://127.0.0.1:5000/airbnb-onepage/;
    }
}
